### ISSUE TITLE
no cpu.txt instructions

### ISSUE THREAD

**Issue by hugopnabais** [Dead2/CryptoGoblin#16]
When I try to run version 4.1.0 for the first time after I configure my pool I get:
Failed to open config file cpu.txt
I don't find anywhere any information on how to create cpu.txt

**Comment by Dead2** [comment]
Please read the big text at the top of the release info for 4.1.0
https://github.com/Dead2/CryptoGoblin/releases/tag/4.1.0

**Comment by chron0** [comment]
this seems still to be the case with 4.3.0

**Comment by Dead2** [comment]
@chron0 Fixed in 4.3.3, thanks for the nudge.

**Comment by chron0** [comment]
thx, much appreciated - and thanks for all the great work with xmrig and xmrig-proxy!
