### ISSUE TITLE
failing to compile with Ubuntu 16.04 on Haswell arch

### ISSUE THREAD

**Issue by PatrickDehkordi** [Dead2/CryptoGoblin#17]
[ 93%] Building ASM object CMakeFiles/CryptoGoblin.dir/xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop.S.o
[ 96%] Building ASM object CMakeFiles/CryptoGoblin.dir/xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.S.o
[100%] Linking CXX executable bin/CryptoGoblin
/usr/bin/ld: warning: -z common ignored.
/usr/lib/gcc/x86_64-linux-gnu/5/include/avxintrin.h: In function 'round_compute':
/usr/lib/gcc/x86_64-linux-gnu/5/include/avxintrin.h:162:0: internal compiler error: in copy_to_mode_reg, at explow.c:617
   return (__m256) __builtin_ia32_andps256 ((__v8sf)__A, (__v8sf)__B);
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
CMakeFiles/CryptoGoblin.dir/build.make:810: recipe for target 'bin/CryptoGoblin' failed
make[2]: *** [bin/CryptoGoblin] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/CryptoGoblin.dir/all' failed
make[1]: *** [CMakeFiles/CryptoGoblin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed

**Comment by Dead2** [comment]
Hm, that is a quite old compiler (GCC 5).
What causes the ICE is not known, but I suspect you might have to disable LTO in build.sh, unless you can install a newer compiler. For haswell, there is not a whole lot that LTO can do to improve hashrates unfortunately, so you probably won't notice any decline.
Please report back whether that solved the problem :)
