### ISSUE TITLE
Will you be updating to allow mining with the new POW change?

### ISSUE THREAD

**Issue by jkelly99** [Dead2/CryptoGoblin#4]
Quick link to the discussion on xmr-stak's repository. [https://github.com/fireice-uk/xmr-stak/issues/1163](https://github.com/fireice-uk/xmr-stak/issues/1163)

FWIW, I'm still using your xmr-stak-cpu fork. But will be updating soon! lol

**Comment by Dead2** [comment]
Sorry for the late answer. Yes, I will release an update. I am only hoping it will not be late for the fork though.

**Comment by Dead2** [comment]
New version released :)
Took a while, but I found out I might as well rebase to upstream again, so lots of new features too. Also spent a lot of time on polishing this release.
https://github.com/Dead2/CryptoGoblin/releases/tag/2.0.0
