### ISSUE TITLE
c++ error in LTO in Ubuntu 16.04

### ISSUE THREAD

**Issue by dancudds** [Dead2/CryptoGoblin#7]
[100%] Linking CXX executable bin/CryptoGoblin
c++: internal compiler error: Killed (program lto1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
lto-wrapper: fatal error: /usr/bin/c++ returned 4 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
CMakeFiles/CryptoGoblin.dir/build.make:670: recipe for target 'bin/CryptoGoblin' failed
make[2]: *** [bin/CryptoGoblin] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/CryptoGoblin.dir/all' failed
make[1]: *** [CMakeFiles/CryptoGoblin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
+ set +x
strip: 'build/bin/CryptoGoblin': No such file

**Comment by Dead2** [comment]
You should try to upgrade your GCC and G++ to newer versions, 6.x or 7.x handle big LTO projects a lot better than 5.x does.

**Comment by dancudds** [comment]
What's the best way of going about this? I've installed gcc-7 but it still uses the stock gcc

**Comment by Dead2** [comment]
In build.sh, set:
cmakeopt="-DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++"
But change the paths to the ones for the GCC-7 compiler of course.

**Comment by dancudds** [comment]
Free memory issue
